spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spaced_repetition_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    jwt:
      secret-key: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
      expiration: 86400000
  application:
    name: spaced-repetition-be
  mail:
    host: localhost
    port: 1025  # MailHog SMTP port
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    org.springframework.web: INFO
    org.hibernate: INFO
    com.hburak_dev: DEBUG

cors:
  allowed-origins: http://localhost:4200
