version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: spaced_repetition_db
    environment:
      POSTGRES_DB: spaced_repetition_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 